(test strings
 (= "xx" (scat "xx" "") (scat "x" "x") (scat "" "xx"))
 (= 4 (slen "slen"))
 (= "ystr" (ystr 'ystr))
 (= 'sym (sym "sym"))
 (~ (ystr (sym)))
 (= "hollow world" (scat "hol" "low " "wor" "ld"))
 (= "bidden" (ssub "forbidden planet" 3 9))
 (= "" (str))
 (= () (chars "") (char ""))
 (= 97 (char "a"))
 (= (L 97 115 100 102) (chars "asdf"))
 (= "asdf" (str 97 115 100 102))
 (: (printable-char) (+ 0x20 (randn (- 0x7e 0x20)))
    (randw) (ap str (map  printable-char(iota (+ 4 (randn 12)))))
    words (map randw (iota 0z100))
  (all (\ word (= word (ap str (chars word)))) words)))
