.de FN
\fI\|\\$1\|\fP
..
.TH LIPS 1 lips
.SH NAME
lips - lisp interpreter
.SH SYNOPSIS
.B lips
.RB [ \-hi_ ]
.RI [ scripts... ]
.SH DESCRIPTION
.B lips
is a simple lisp interpreter.
.P
With no arguments, start a repl.
.SH OPTIONS
.TP
.B \-h
show help
.TP
.B \-i
start repl unconditionally
.TP
.B \-_
don't bootstrap
.SH FILES
.TP
.FN /usr/local/lib/lips/prelude.lips
The system-wide bootstrap script.
.TP
.FN ~/.local/lib/lips/prelude.lips
The individual bootstrap script. Overrides the system-wide script if present.
.SH LICENSE
Public domain.
