.TH LIPS 1 lips
.SH NAME
lips - lisp interpreter
.SH SYNOPSIS
.B lips
.RB [ \-hi_ ]
.RI [ scripts... ]
.SH DESCRIPTION
.B lips
is a simple lisp interpreter.
.P
With no arguments, start a repl.
.SH OPTIONS
.TP
.B \-h
show help
.TP
.B \-i
start repl unconditionally
.TP
.B \-_
don't bootstrap
.SH LICENSE
Public domain.
