.de FN
\fI\|\\$1\|\fP
..
.TH LISA 1 lisa
.SH NAME
lisa - lisp interpreter
.SH SYNOPSIS
.B lisa
.RB [ \-hi_ ]
.RI [ scripts... ]
.SH DESCRIPTION
.B lisa
(LISt Action) is a lisp interpreter.
.P
With no arguments, start a repl.
.SH OPTIONS
.TP
.B \-h
show help
.TP
.B \-i
start repl unconditionally
.TP
.B \-_
don't bootstrap
.SH SPECIAL FORMS
.I (\\\\)   ; empty function returns nil
.br
.I (\\\\ x) ; thunk evaluates x
.br
.I (\\\\ a b x) ; a and b are arguments, x is the body
.br
.I (\\\\ a b . x) ; variadic in b
.RS
.B make a function
.RE
.PP
.I (? a b) ; b if a else nil
.br
.I (? a b c) ; b if a else c
.br
.I (? a b c d e) ; b if a else d if c else e ; etc.
.RS
.B choose an option
.RE
.PP
.I (, a b c) ; eval a, then b, then c; value is c
.RS
.B do things in order
.RE
.PP
.I (: a b c d ...) ; let a := b, c := d ... in current scope
.br
.I (: a b c d ... e) ; let a := b, c := d ... in e
.br
.I (: (a b c) d) ; = (: a (\\\\ b c d))
.RS
.B name values
.RE
.PP
.I (` (1 2 3)) ; or '(1 2 3)
.RS
.B suppress evaluation
.RE
.SH FILES
.TP
.FN /usr/local/lib/lisa/lisa.la
The system-wide bootstrap script.
.TP
.FN ~/.local/lib/lisa/lisa.la
The individual bootstrap script. Overrides the system-wide script if present.
.SH LICENSE
Public domain.
